# Use an existing docker image, set it's port and mount a local file to be served by nginx


# Basic docker compose to create a web app using nginx image
# version: '3'
# services:
#   web:
#     image: nginx
#     ports:
#       - "8080:80"
#     volumes:
#       - ./html:/usr/share/nginx/html


# Broswer sync hot reload for static files work with the below docker command 
# we are downloading browser-sync and make it listen to port 3000 and in the html file we can list out the <head> to point to the browser sync
# docker run --rm -it -p 3000:3000 -v "${PWD}/html:/site" -w /site node bash -c "npm install -g browser-sync && browser-sync start --server --files '*.html'"

# and the below one is a docker compose version
version: '3.8'

services:
  browsersync:
    image: node:18
    container_name: browsersync-dev
    working_dir: /app
    volumes:
      - ./html:/app
    ports:
      - "3000:3000"
      - "3001:3001"  # Optional: UI port (if you want access later)
    command: >
      sh -c "npm install -g browser-sync &&
             browser-sync start --server --files '*.html' --no-open --inject-changes"


 