name: CI - Build Docker App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose stack
        run: docker compose -f docker-compose.yml up --build -d

      - name: Test backend container (example)
        run: docker exec node-backend curl http://localhost:4000/visits || echo "Backend failed"

      - name: Shutdown
        run: docker compose down
